import os
import dspy
from typing import Optional
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

lm = dspy.LM("openai/gpt-4o", api_key=os.getenv('OPENAI_API_KEY'), temperature=0)
dspy.configure(lm=lm)
 
def ai(user_prompt: str, system_prompt: Optional[str] = None):
    class QA(dspy.Signature):
        __doc__ = system_prompt
        
        user_prompt: str = dspy.InputField(desc="The user's request.")
        response: str = dspy.OutputField(desc="The text response generated by the language model.")
        
    predict = dspy.Predict(QA)
    return predict(user_prompt=user_prompt).response
